name: scaling-writers
workload_type: performance
mode: write
duration_seconds: 120
concurrency:
  writers: [1,2,4]
operations:
  write:
    event_size_bytes: 256
streams:
  distribution: uniform
  count: 10000
#stores: [dummy]
#stores: [umadb, dummy]
stores: [umadb]
